version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flagcraft-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feature_flags
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d feature_flags']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flagcraft-redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: flagcraft-api
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/feature_flags
      REDIS_URL: redis://redis:6379
      PORT: 3001
      BETTER_AUTH_SECRET: flagcraft_production_secret_change_me
      BETTER_AUTH_URL: http://localhost:3001
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    container_name: flagcraft-dashboard
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      INTERNAL_API_URL: http://api:3001
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - api

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: flagcraft-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:10.4.1
    container_name: flagcraft-grafana
    ports:
      - '3005:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  pgdata:
  grafana_data:
